AWSTemplateFormatVersion: '2010-09-09'
Description: Simple EC2 instance using CloudFormation

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    Description: EC2 instance type

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: ami-0c02fb55956c7d316

Outputs:
  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref EC2Instance